# Generated by Django 3.1.3 on 2021-08-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20210804_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_mark',
            new_name='grade',
        ),
    ]
